services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - tonoya_net
    develop:
      watch:
        - action: rebuild
          path: ./src
    ports:
      - "127.0.0.1:4000:4000"

networks:
  tonoya_net:
    name: tonoya_net
    driver: bridge
